### ISSUE TITLE
Only deploy commits signed by a specific GPG key

### ISSUE THREAD

**Issue by ilovethensa** [nlewo/comin#52] opened 2024-08-10 10:09 UTC
I love comin, but i have concerns about a single-point-of-failure, if someone gets access to my github account all my machines could be compromised, so i propose making comin have an option to only deploy commits signed by a specific GPG key

**Comment by nlewo** [comment] 2024-08-11 16:46
Close as duplicate of https://github.com/nlewo/comin/issues/29

**Closed by nlewo** 2024-08-11 16:46 UTC
